### ISSUE TITLE
Stopped Working For Me T_T

### ISSUE THREAD

**Issue by karimawi** [hallzy/sort-youtube-add-to-playlist#1]
prob. YouTube changed some stuff, but let me know if it's working for you, Thanks.

**Comment by hallzy** [comment]
Still works for me...

**Comment by hallzy** [comment]
I  also don't know when you last updated this, but a few weeks ago YouTube did change some stuff and it was broken, but it has since been fixed.

**Comment by karimawi** [comment]
Yeah, that was my bad, I updated it, works now, thanks.
